name       : tigervnc
version    : 1.8.0
release    : 1
source     :
    - https://github.com/TigerVNC/tigervnc/archive/v1.8.0.tar.gz : 9951dab0e10f8de03996ec94bec0d938da9f36d48dca8c954e8bbc95c16338f8
license    : GPL-2.0 
component  : network.util
summary    : Virtual Network Computing (VNC) is a remote display system which allows you to view and interact with a virtual desktop environment that is running on another computer on the network. 
description: |
    Virtual Network Computing (VNC) is a remote display system which allows you to view and interact with a virtual desktop environment that is running on another computer on the network.   
builddeps  :
    - pkgconfig(libturbojpeg)
    - pkgconfig(x11-xcb) 
    - pkgconfig(xorg-server)
    - pkgconfig(xrender)
    - extra-cmake-modules
    - fltk-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
