name       : tigervnc
version    : 1.9.0
release    : 3
source     :
    - https://github.com/TigerVNC/tigervnc/archive/v1.9.0.tar.gz : f15ced8500ec56356c3bf271f52e58ed83729118361c7103eab64a618441f740
license    : GPL-2.0-or-later
component  : network.util
summary    : Virtual Network Computing (VNC) is a remote display system which allows you to view and interact with a virtual desktop environment that is running on another computer on the network.
description: |
    Virtual Network Computing (VNC) is a remote display system which allows you to view and interact with a virtual desktop environment that is running on another computer on the network.
builddeps  :
    - pkgconfig(libturbojpeg)
    - pkgconfig(x11-xcb)
    - pkgconfig(xorg-server)
    - pkgconfig(xrender)
    - extra-cmake-modules
    - fltk-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
